version: '2'
services:
    pchauvetonheroku-app:
        image: pchauvetonheroku
        external_links:
            - pchauvetonheroku-postgresql:postgresql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/pchauvetonheroku
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    pchauvetonheroku-postgresql:
        extends:
            file: postgresql.yml
            service: pchauvetonheroku-postgresql
