version: '2'
services:
    pchauvetonheroku-postgresql:
        container_name: pchauvetonheroku-postgresql
        image: postgres:9.5.4
        # volumes:
        #     - ~/volumes/jhipster/pchauvetonheroku/postgresql/:/var/lib/postgresql/
        environment:
            - POSTGRES_USER=pchauvetonheroku
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
